### ISSUE TITLE
HA configuration - stack smashing detected

### ISSUE THREAD

**Issue by rwojsznis** [typesense/typesense#1552]
## Description

First of all - HUGE thank you for open-sourcing this. I can't believe how awesome typesense is ❤️ 

I'm running typesense in HA manner in k8s - setup is [loosely based on this repo](https://github.com/sai3010/Typesense-Kubernetes-Operator) - we have a headless service, 3 replica sets and we're using `reset-peers-on-error` [as suggested here](https://github.com/typesense/typesense/issues/465)

## Steps to reproduce

Statefulset runs more-or-less as:

```
containers:
        - name: typesense
          image: typesense/typesense:0.26.0.rc50
          command:
            - /opt/typesense-server
            - '-d'
            - /usr/share/typesense/data
            - '-a'
            - 'key--please-change'
            - '--api-port'
            - '8108'
            - '--peering-port'
            - '8107'
            - '--nodes'
            - /usr/share/typesense/nodes
            - '--reset-peers-on-error'
```

In the `/usr/share/typesense/nodes` we have list of nodes [similar to this](https://gist.github.com/prabhatsharma/c128fa54183be8e26915f48a164a436b#file-typesense-statefulset-3-replica-yaml-L35)

It _seems_ like `reset-peers-on-error` is causing a process crash; restarting a single node results in a cascading failure:

```
Server[braft::RaftStatImpl+braft::FileServiceImpl+braft::RaftServiceImpl+braft::CliServiceImpl] is serving on port=8107.                                                                                                                                                  
server.cpp:1110] Check out http://typesense-host-1:8107 in web browser.
raft_server.cpp:174] Unable to resolve host: typesense-host-0.typesense-service.typesense-namespace.svc.cluster.local   
raft_server.cpp:174] Unable to resolve host: typesense-host-2.typesense-service.typesense-namespace.svc.cluster.local
*** stack smashing detected ***: terminated                                                                   
```

Process crashes; destroying whole statefulset seems to _fix_ the state of the cluster.

This is quite odd, as seems like nobody encountered `stack smashing detected` before, at last according to the GH issues search 😅 

## Expected Behavior

Process not crashing upon node leaving the cluster.

## Actual Behavior

Process crash.

## Metadata

**Typesense Version**: typesense 0.25.2 to 0.26.0.rc50

**OS**: latest ubuntu LTS, checked both arm64/amd64, running on AWS (EC2)
