### ISSUE TITLE
Collections getting dropped / lost

### ISSUE THREAD

**Issue by donchev7** [typesense/typesense#1819]
## Description

We have job running every minute that processes files and indexes them:
```
await collection.documents().upsert(news, { action: 'emplace' })
```

We are running typesense 26.0. Single node in kubernetes with the following config:
```
TYPESENSE_DATA_DIR: /data
TYPESENSE_API_PORT: "8108"
TYPESENSE_API_KEY:  "xyz"
```

We notice that the job works for 6-12h and suddenly we receive errors that the collection cannot be found:

<img width="1263" alt="Screenshot 2024-07-03 at 13 00 03" src="https://github.com/typesense/typesense/assets/11960967/8aa0c6fc-ecae-4473-b338-d5fffac8e405">

During that time when this happens we dont see anything strange in the typesense server:

<img width="1263" alt="Screenshot 2024-07-03 at 13 00 03" src="https://github.com/typesense/typesense/assets/11960967/8618f6f5-f327-4691-8c8c-3d9298af658f">

The question I have is under which circumstance does typesense lose/drop collections? Is this because of the frequent indexing operations? 

## Expected Behavior

To not lose collections

## Actual Behavior

Collections getting dropped / lost

## Metadata

**Typesense Version**:
26.0

**OS**:
Linux - single node on K8s

**Comment by kishorenc** [comment]
We have not encountered such a problem in any cluster running on Typesense (we run thousands of clusters in TS Cloud), so I suspect that the issue is something environment specific. Please check that you are not using some ephemeral disk or volume.

**Comment by Aneerudh2k2** [comment]
@kishorenc and @donchev7 
I faced the same issue, in my case collection exists but documents which are shown `success: true` on indexing, after some time (after few hours) all the data are lost. When I checked with `/collection/<collection_id>` api endpoint it returned this output.

<img width="372" alt="Image" src="https://github.com/user-attachments/assets/d6c5fdd4-0c4a-4f47-a7b8-107ac3ccbe11" />

**Comment by kishorenc** [comment]
@Aneerudh2k2 

How are you deploying Typesense and what type of disk are you using?

**Comment by Aneerudh2k2** [comment]
@kishorenc 
Deployment is done through docker with k8 and disk type is AWS gp3 EBS. Let me know if you need anything else.

**Comment by kishorenc** [comment]
I'm not sure what could be going wrong. It's unlikely to be a bug on Typesense side because this is such a fundamental issue and will definitely show up more widely if there is a bug.

**Comment by arturkasperek** [comment]
@kishorenc I experienced the same behaviour on EKS. Using default gp3 disks and things gone after couple hours. I'm using typesense `28.0`.
Dockerfile:
```dockerfile
FROM typesense/typesense:28.0

CMD [ "--data-dir", "/data", "--api-key", "<removed>", "--enable-cors" ]
```
Deployment file:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment-typesense
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-svc-typesense
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        karpenter.sh/do-not-disrupt: "true"
      creationTimestamp: null
      labels:
        app: search-svc-typesense
        app.kubernetes.io/part-of: search-svc-typesense
        pod-type: standard
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - search-svc-typesense
              topologyKey: topology.kubernetes.io/zone
            weight: 100
      containers:
      - env:
        - name: CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: main
              divisor: 1m
              resource: requests.cpu
        - name: CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: main
              divisor: 1m
              resource: limits.cpu
        - name: MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: main
              divisor: 1Mi
              resource: requests.memory
        - name: MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: main
              divisor: 1Mi
              resource: limits.memory
        image: 259174207142.dkr.ecr.us-east-1.amazonaws.com/search-typesense:main-c2ee72d5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8108
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: main
        ports:
        - containerPort: 8108
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8108
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 6
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1500m
            ephemeral-storage: 100Mi
            memory: 1536Mi
          requests:
            cpu: "1"
            ephemeral-storage: 50Mi
            memory: 1Gi
        securityContext:
          runAsGroup: 0
          runAsUser: 0
        volumeMounts:
        - mountPath: /data
          name: typesense
      securityContext:
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
      volumes:
      - name: typesense
        persistentVolumeClaim:
          claimName: search-svc-typesense-pvc
```

After SSHing I saw that files are there and even due to the fact that pod was restarted:

<img width="794" alt="Image" src="https://github.com/user-attachments/assets/d575a03a-6f0d-42c8-8404-622370c506f0" />

Also noticed that data gone even without restarting a pod with deployment after couple hours - it seems something is wrong

**Comment by Aneerudh2k2** [comment]
Hey @kishorenc 
I tried setting it up locally with Docker, but ran into the same issue. Attached yaml file and volume folder for reference


```yaml
services:
  typesense:
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./volume/typesense:/data
    command: "--data-dir /data --api-key=typesense --enable-cors"
```

<img width="215" alt="Image" src="https://github.com/user-attachments/assets/e2cdce14-dd33-45a2-8054-71168fe54633" />
