### ISSUE TITLE
[BUG] Snapshots are not being cleaned, utilising disk space to 100% (26.0)

### ISSUE THREAD

**Issue by ivankuznetsov** [typesense/typesense#1891]
## Description

Here's the corrected version of your bug report:
Snapshots are not being cleaned at all, so after some time we get an endless amount of snapshots despite only needing the last one, as well as an endless log without rotation. After some time it utilizes 100% of the container's disk space and dies.

## Steps to reproduce: 

1. Install Typesense and run with the following parameters:

```
[root@typesense-prod-clone typesense]# cat /etc/typesense/typesense-server.ini
; Typesense Configuration

[server]

api-address = 0.0.0.0
api-port = 8108
data-dir = /var/lib/typesense
api-key = Z97s1KK2k82Imx5dTpbTc0JtMZEF5NkeEzCXy9uyPWN7aKhh
log-dir = /var/log/typesense
db-compaction-interval = 86400
```

2. Add few collections

3. Check the snapshots folder:
```
[root@typesense-prod-clone typesense]# find -name \*sst | xargs ls -isla | sort -n
 33900301  66048 -rw-r--r--. 2 root root  67630210 Aug  2 08:01 ./db/1113110.sst
 33900301  66048 -rw-r--r--. 2 root root  67630210 Aug  2 08:01 ./state/snapshot/snapshot_00000000000003635623/db_snapshot/1113110.sst
 33900310  65976 -rw-r--r--. 2 root root  67558016 Aug  2 08:01 ./db/1113111.sst
 33900310  65976 -rw-r--r--. 2 root root  67558016 Aug  2 08:01 ./state/snapshot/snapshot_00000000000003635623/db_snapshot/1113111.sst
 33900321  65980 -rw-r--r--. 2 root root  67560113 Aug  2 08:01 ./db/1113112.sst
 33900321  65980 -rw-r--r--. 2 root root  67560113 Aug  2 08:01 ./state/snapshot/snapshot_00000000000003635623/db_snapshot/1113112.sst
...
```

## Expected Behavior

1. Snapshots should be cleaned automatically by default as they are created automatically (for 90% of applications, I suppose one last snapshot is enough).
2. There should be a parameter for how many snapshots to keep by default. 

## Actual Behavior

1. Snapshots are not getting cleaned.
2. Snapshots take up 100% of disk space, no matter how big the disk is.

## Metadata

CentOS Stream 9
docker-ce 27.1.1

docker-compose: 

```
services:
    typesense:
        image: typesense/typesense:26.0
        network_mode: host
        command: --config=/etc/typesense/typesense-server.ini
        volumes:
            - /etc/typesense/typesense-server.ini:/etc/typesense/typesense-server.ini
            - /var/lib/typesense:/var/lib/typesense
            - /var/log/typesense:/var/log/typesense
        restart: always`
```
