### ISSUE TITLE
Typesense cluster in a Docker Swarm, the API key stops working after restarting a node's Docker engine.

### ISSUE THREAD

**Issue by chanhee-kang** [typesense/typesense#1914]
## Description

When running a Typesense cluster in a Docker Swarm environment, the admin key stops working after restarting a node's Docker engine.

## Steps to reproduce
1. Starts a Typesense cluster in Docker Swarm environment with `docker stack deploy typesense-cluster`
- docker-compose.yml : 
```
version: '3.8'

services:
  typesense1:
    image: typesense/typesense:26.0
    volumes:
      - /typesense_cluster/data1:/data
      - /typesense_cluster/nodes:/nodes
    ports:
      - "8108:8108"
      - "8107:8107"
    
    command: ["--peering-subnet","10.11.0.0/16","--data-dir", "/data","--api-key", "password","--nodes","/nodes/nodes","--peering-port","8107","--api-port","8108","--enable-cors"]
    
    environment:
      - TYPESENSE_RESET_PEERS_ON_ERROR=TRUE 
      - TYPESENSE_LOG_LEVEL=warn
      - TYPESENSE_HEALTH_CHECK_INTERVAL_SECONDS=60
      - TYPESENSE_SNAPSHOT_INTERVAL_SECONDS=7200
      - TYPESENSE_DISABLE_STARTUP_LOGS=true
      - TYPESENSE_ENABLE_USAGE_LOGGING=false
    deploy:
      # endpoint_mode: dnsrr
      replicas: 1
      labels:
        feature.description: “typesense1”
      restart_policy:
        condition: any
      placement:
        constraints: [node.hostname == node-1]
    
    networks:
      - ts_net2
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  typesense2:
    image: typesense/typesense:26.0
    hostname : typesense2
    volumes:
      - /typesense_cluster/data2:/data
      - /typesense_cluster/nodes:/nodes
    ports:
      - "8108:8108"
      - "8107:8107"
    command: ["--peering-subnet","10.11.0.0/16","--data-dir", "/data","--api-key", "password","--nodes","/nodes/nodes","--peering-port","8107","--api-port","8108","--enable-cors"]
    
    environment:
      - TYPESENSE_RESET_PEERS_ON_ERROR=TRUE 
      - TYPESENSE_LOG_LEVEL=warn
      - TYPESENSE_HEALTH_CHECK_INTERVAL_SECONDS=60
      - TYPESENSE_SNAPSHOT_INTERVAL_SECONDS=7200
      - TYPESENSE_DISABLE_STARTUP_LOGS=true
      - TYPESENSE_ENABLE_USAGE_LOGGING=false
    deploy:
      # endpoint_mode: dnsrr
      replicas: 1
      labels:
        feature.description: “typesense2”
      restart_policy:
        condition: any
      placement:
        constraints: [node.hostname == node-2]
    
    networks:
      - ts_net
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  typesense3:
    image: typesense/typesense:26.0
    hostname : typesense3
    volumes:
      - /typesense_cluster/data3:/data
      - /typesense_cluster/nodes:/nodes
    ports:
      - "8108:8108"
      - "8107:8107"
    command: ["--peering-subnet","10.11.0.0/16","--data-dir", "/data","--api-key", "password","--nodes","/nodes/nodes","--peering-port","8107","--api-port","8108","--enable-cors"]
    environment:
      - TYPESENSE_RESET_PEERS_ON_ERROR=TRUE 
      - TYPESENSE_LOG_LEVEL=warn
      - TYPESENSE_HEALTH_CHECK_INTERVAL_SECONDS=60
      - TYPESENSE_SNAPSHOT_INTERVAL_SECONDS=7200
      - TYPESENSE_DISABLE_STARTUP_LOGS=true
      - TYPESENSE_ENABLE_USAGE_LOGGING=false
    deploy:
      # endpoint_mode: dnsrr
      replicas: 1
      labels:
        feature.description: “typesense3”
      restart_policy:
        condition: any
      placement:
        constraints: [node.hostname == node-3]
    
    networks:
      - ts_net
    logging:
      options:
        max-size: "10m"
        max-file: "5"


  typesense_dashboard:
      container_name: admin_dashboard
      image: ghcr.io/lewynation/typesense-admin-dashboard:latest
      restart: always
      networks:
        - ts_net
      ports:
        - 18109:3000


networks:
  ts_net:
    external: true


```
2. Shut down and the restart the Docker engine on one of the node with `sudo systemctl start docker`
3. Attempt to use the Typesense admin key

## Expected Behavior
The Typesense admin key should continue to work after restarting a node's Docker engine.

## Actual Behavior
The Typesense admin key no longer works, resulting in authentication failures for admin operations.
```
2024-08-26 09:55:32.482 | ERROR    | backend.libs.typesense:hybrid_search_requestsummary:208 - Failed to perform hybrid search: [Errno 401] Forbidden - a valid x-typesense-api-key header must be sent.
2024-08-26 09:55:32.487 | ERROR    | backend.libs.typesense:hybrid_search_screeninfo:226 - Failed to perform hybrid search on screeninfo: [Errno 401] Forbidden - a valid x-typesense-api-key header must be sent.
```

## Metadata

**Typesense Version**: typesense/typesense:26.0
**OS**: Ubuntu 22.04
**Environment**: Docker Swarm

## Additional Information
- This issue consistently occurs when restarting a node's Docker engine
- The problem persists even after the node rejoins the swarm
- Other non-admin operations seem to work fine

Any assistance in resolving this issue would be greatly appreciated. Thank you!
