### ISSUE TITLE
Introduce major version tags for docker images

### ISSUE THREAD

**Issue by alexander-schranz** [typesense/typesense#2018]
## Description

Currently there is no docker tag like `26` or `27` to get the latest version. It would be nice to have something like this. Similar meilisearch created: https://github.com/meilisearch/meilisearch/discussions/4759#discussioncomment-9935703. This make it easier for lib authors test always against the latest of a specific version.

## Steps to reproduce

```
services:
  typesense:
    image: typesense/typesense:27
    ports:
      - "8108:8108"
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: S3CR3T
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - typesense-data:/data
```

```
docker compose up
```

## Expected Behavior

Have for major version also a tag (26, 27, ...)

## Actual Behavior

No tag to get latest major version is possible.

## Metadata

**Typesense Version**: want latest

**OS**: Docker on MacOS (arm)
