### ISSUE TITLE
Documentation for SSL-secured Typesense cluster in Kubernetes

### ISSUE THREAD

**Issue by enzolry** [typesense/typesense#2102]
## Description

I think there is a lack of documentation regarding the setup of a SSL-secured Typesense cluster in Kubernetes.

There are two available flags : --ssl-certificate and --ssl-certificate-key but even if you provide them (which allows the server to start), there are constant warnings in the slave pod logs saying "Unable to locate system SSL certificates".

To solve this issue, it's necessary to provide the CA certificate file at one of the hardcoded locations listed inside the [source code](https://fossies.org/linux/typesense/src/http_client.cpp) of the `HttpClient::init` method like `/etc/ssl/certs/ca-certificates.crt`. I don't understand why there isn't a separate flag for this file. It should probably not be hardcoded like it is, maybe there are reasons to do it this way ?

## Steps to reproduce

1) Create typesense namespace :

`kubectl create namespace typesense`

2) Create typesense-ssl secret which will be mounted in `/etc/ssl/certs` (without ca-certificates.crt for now) :

`kubectl -n typesense create secret generic typesense-ssl --from-file=tls.crt=/path/to/tls.crt --from-file=tls.key=/path/to/tls.key --save-config`

3) Create the typesense-api-key secret : 

`kubectl -n typesense create secret generic typesense-api-key --from-literal=api-key=<api_key> --save-config`

4) Apply the config : 

```
apiVersion: v1
kind: Namespace
metadata:
  name: typesense
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: typesense
  namespace: typesense
  labels:
    app: typesense
spec:
  serviceName: headless
  podManagementPolicy: Parallel
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: typesense
  template:
    metadata:
      labels:
        app: typesense
    spec:
      serviceAccountName: typesense-service-account
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: typesense
          image: typesense/typesense:27.1
          args:
            - "--data-dir=/usr/share/typesense/data"
            - "--api-key=$(TYPESENSE_API_KEY)"
            - "--enable-ssl"
            - "--ssl-certificate=/etc/ssl/certs/tls.crt"
            - "--ssl-certificate-key=/etc/ssl/certs/tls.key"
            - "--peering-port=8107"
            - "--api-port=443"
            - "--enable-cors"
            - "--nodes=/usr/share/typesense/nodes"
            - "--reset-peers-on-error"
          ports:
            - containerPort: 443
            - containerPort: 8107
          volumeMounts:
            - name: data
              mountPath: /usr/share/typesense/data
            - name: nodeslist
              mountPath: /usr/share/typesense
            - name: ssl-certs
              mountPath: /etc/ssl/certs
          env:
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: typesense-api-key
                  key: api-key
          readinessProbe:
            httpGet:
              path: /health
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
        - name: typesense-node-resolver
          image: alasano/typesense-node-resolver
          command:
            - "/opt/tsns"
            - "-namespace=typesense"
            - "-service=headless"
            - "-nodes-file=/usr/share/typesense/nodes"
            - "-peer-port=8107"
            - "-api-port=443"
          volumeMounts:
            - name: nodeslist
              mountPath: /usr/share/typesense
          readinessProbe:
            exec:
              command:
                - cat
                - /usr/share/typesense/nodes
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            exec:
              command:
                - cat
                - /usr/share/typesense/nodes
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
      volumes:
        - name: ssl-certs
          secret:
            secretName: typesense-ssl
        - name: nodeslist
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: headless
  namespace: typesense
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: typesense
  ports:
    - name: api
      port: 443
      targetPort: 443
    - name: internal
      port: 8107
      targetPort: 8107
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  namespace: typesense
spec:
  selector:
    app: typesense
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: typesense-service-account
  namespace: typesense
imagePullSecrets:
  - name: dockerhub-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: typesense
  name: typesense-role
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["watch", "list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: typesense-role-binding
  namespace: typesense
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: typesense-role
subjects:
  - kind: ServiceAccount
    name: typesense-service-account
    namespace: typesense
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: typesense-pdb
  namespace: typesense
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: typesense
```

5) When the pods are running, go through the logs of each pod to see the warning inside the slave pod logs

`kubectl -n typesense get pods`

`kubectl -n typesense logs pod/typesense-0`

`kubectl -n typesense logs pod/typesense-1`

`kubectl -n typesense logs pod/typesense-2`

6) Provide the ca-certificates.crt file in the typesense-ssl secret

`kubectl -n typesense delete secret typesense-ssl`

`kubectl -n typesense create secret generic typesense-ssl --from-file=tls.crt=/path/to/tls.crt --from-file=tls.key=/path/to/tls.key --from-file=ca-certificates.crt=./path/to/ca-certificates.crt --save-config`

7) Restart the statefulset by deleting the pods

`kubectl delete pods -l app=typesense -n typesense`

8) Same as point 5, but warnings are gone from slave pod logs

## Expected Behavior

The server should fail to start if the certificate and the key provided with --ssl-certificate and --ssl-certificate-key flags are not certified with a matching ca-certificates.crt file and it should give some instructions inside the logs.

## Actual Behavior

The server starts but the slave pods have constant warnings in their logs without clear instructions.

## Metadata

**Typesense Version**: 27.1

**OS**: Linux Ubuntu 20.04
