### ISSUE TITLE
RAG: support /chat/completions API (provider-independent)

### ISSUE THREAD

**Issue by stargazer33** [typesense/typesense#2154]
I think that having built-in RAG feature in Typesense is really great! BUT. It might be... improved a bit. I am reading documentation:

> Typesense currently supports the following LLM platforms:
>    OpenAI
>    Cloudflare Workers AI
>    vLLM

Well, in my experience, the platforms supporting /chat/completions API are QUITE compatible. Almost 100% compatible. I have some code working with the following /chat/completions API providers:
```
api.fireworks.ai
api.omnistack.sh
api.scaleway.ai
api.cerebras.ai
api.deepinfra.com
glhf.chat
api.groq.com
openrouter.ai
api.sambanova.ai
api-inference.huggingface.co
api.together.xyz
```
(there are much more providers, and there are new providers popping up all the time)

And my client code is the same! Well, I have configuration files, per provider,
and I found out that one provider didn't support one feature (specifying "seed"),
so I changed the corresponding config file, that's it.

**My point is: Typesense can rely on /chat/completions API**

And you can just write in Typesense documentation:
1. RAG uses /chat/completions API ...
2.  ... the following parameters of /chat/completions should be supported by provider: ...
3. ... we tested Typesense RAG with the following /chat/completions API providers: ...

P.S. I really want to test RAG feature, but have no OpenAI / CloudFlare account, and can not run big models locally with vLLM... Would like to use something like this https://deepinfra.com/meta-llama/Llama-3.3-70B-Instruct-Turbo - the most cheap 70B model I found...

**Comment by stargazer33** [comment]
You can rely on community to test RAG feature with different providers/models/model parameters.
Somehow, the results of these tests have to be collected in one place.

**Comment by stargazer33** [comment]
Implementation hint: you might use the following provider-specific config file:
```YAML
#
# the "/chat/completions" should be just appended to the baseUrl
#
baseUrl: https://api.omnistack.sh/openai/v1

#
# omnistack-specific name for "llama-3.3-70b-specdec"
#
model: cecelia_milan_mylene

# negative values of some parameters means "not set"
#

#
# provider-specific limits
#
limitReqDay: 7000
limitReqMin: -1
limitTokDay: -1
limitTokMin: -1

# Optional provider-specific HTTP headers.
# "x-wait-for-model" shown here as an example, only huggingface use it
httpHeaders:
  x-wait-for-model: true

frequencyPenalty: -100
presencePenalty: -100
#
# "seed" is not supported by this provider
seed: -1
stop:
stream: false
temperature: 0.0
topP: 0.01
maxTokens: 4096
```
