### ISSUE TITLE
Ability to pass arguments via config file

### ISSUE THREAD

**Issue by kishorenc** [typesense/typesense#41]
## Description

Need a way to pass in options via a config file rather than the command line. This is a blocker for https://github.com/typesense/typesense/issues/40.

## Steps to reproduce

NA

## Expected Behavior

NA

## Actual Behavior

NA

## Metadata

**Typsense Version**: `0.9.0 and below`

**OS**: `all`

**Comment by guillaumevincent** [comment]
Hello,
in a docker-compose file I'm forced to use this syntax:

```
  search:
    image: typesense/typesense:0.9.2
    volumes:
      - ./search/data:/data
    ports:
      - 8108:8108
    environment:
      API_KEY: abcd
    entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=$${API_KEY}"
```

It could great to follow 12factor app and start looking for .env file, or env variables when you try to make your app configurable.
