### ISSUE TITLE
Indexing performance seems a bit slow

### ISSUE THREAD

**Issue by tkhadimullin** [typesense/typesense#411]
## Description

I'm 6.5 hours into ingesting 1Mil StackOverflow comments from SQL Server to Typesense. My application is still running and I think this should not take so long.

## Steps to reproduce

I'm using an old DB copy from here: https://downloads.brentozar.com/StackOverflow2010.7z (happy to elaborate more on how to set it up)
Spinning the containers up like so:

```yaml
version: '3'
services:
    typesense:
        image: typesense/typesense:0.21.0
        volumes:
            - $PWD/typesense_data:/data
        ports:
            - "8108:8108"
        command: "--data-dir /data --api-key=123123"
    sql-server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        volumes:
            - $PWD/StackOverflowDb:/var/opt/stackoverflow
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=your5ecur3p@ssw0rd
    opensearch:
        image: opensearchproject/opensearch
        restart: unless-stopped
        ports:
            - "9200:9200"
        environment:
            - discovery.type=single-node
        volumes:
            - $PWD/opensearch_data:/usr/share/opensearch/data
    solr:
        image: bitnami/solr
        restart: unless-stopped
        ports:
            - "8983:8983"
        volumes:
            - $PWD/solr_data:/bitnami
        environment:
            - SOLR_CORE=my_core
            - SOLR_COLLECTION=comments            - 
```
and using the following C# code to pull data from SQL Server and index into respective engines:

```csharp
/*
install 
<NuGetReference>NEST</NuGetReference>
<NuGetReference>SolrNet</NuGetReference>
<NuGetReference>Typesense</NuGetReference>
*/

using CommonServiceLocator;
using Microsoft.Extensions.DependencyInjection;
using SolrNet;
using System.Threading.Tasks;
using Typesense;
using Typesense.Setup;
using Nest;

public abstract class SearchEngineClient
{
	public abstract Task IndexAsync(Comments obj);
	public virtual async Task CommitAsync() {/* do nothing by default */}
}

async Task Main()
{
	var clients = new List<SearchEngineClient> {
		new TypeSenseClient(),
		new SolrClient(),
		new OpenSearchClient(),
	};

	foreach (var client in clients)
	{
		var clientName = client.GetType().Name;
		Console.WriteLine($"Testing {clientName}");
		Stopwatch sw = new Stopwatch();
		sw.Start();
		foreach (var c in Comments.Take(1000000)) await client.IndexAsync(c); // this leverages LINQPad's built-in data access driver, but the idea is SELECT TOP(1000000) * FROM Comments
		await client.CommitAsync();
		sw.Stop();
		Console.WriteLine($"Finished {clientName} - {sw.ElapsedMilliseconds} ms");
	}
}

class TypeSenseClient : SearchEngineClient
{
	private class CommentsDto
	{
		public string Id { get; set; }
		public string Text { get; set; }
	};

	private readonly ITypesenseClient typesenseClient;
	public TypeSenseClient()
	{
		var provider = new ServiceCollection()
						.AddTypesenseClient(config =>
						{
							config.ApiKey = "123123";
							config.Nodes = new List<Node>
							{
									new Node
									{
										Host = "localhost",
										Port = "8108",
										Protocol = "http"
									}
							};
						})
						.BuildServiceProvider();

		typesenseClient = provider.GetService<ITypesenseClient>();
		var _ = typesenseClient.DeleteCollection("Comments").Result;

		var schema = new Schema
		{
			Name = "Comments",
			Fields = new List<Typesense.Field>
							{
								new Typesense.Field("id", Typesense.FieldType.String, false),
								new Typesense.Field("text", Typesense.FieldType.String, false),
							},
		};

		var createCollectionResult = typesenseClient.CreateCollection(schema).Result;
	}

	public override async Task IndexAsync(Comments obj)
	{		
		var dto = new CommentsDto { Id = obj.Id.ToString(), Text = obj.Text}; // Typesense requires document Id to be string. While in SQL it is integer. We'll have to adapt a bit
		var createDocumentResult = await typesenseClient.CreateDocument<CommentsDto>("Comments", dto);
	}
}

class SolrClient : SearchEngineClient
{
	private ISolrOperations<Comments> _solr;
	public SolrClient()
	{
		Startup.Init<Comments>("http://localhost:8983/solr/my_core");
		_solr = ServiceLocator.Current.GetInstance<ISolrOperations<Comments>>();
	}
	
	public override async Task IndexAsync(Comments obj) => _solr.Add(obj);

	public override async Task CommitAsync() => _solr.Commit();
}

class OpenSearchClient : SearchEngineClient
{
	private ElasticClient _client;
	public OpenSearchClient()
	{
		var node = new Uri("http://localhost:9200");
		var settings = new ConnectionSettings(node);
		_client = new ElasticClient(settings);
	}

	public override async Task IndexAsync(Comments obj) => _client.Index(obj, idx => idx.Index("comments"));
}
```

## Expected Behavior

Expecting indexing to take comparable time as other engines for baseline:
*OpenSearch*: 5294173ms (88 mins)
*Solr*: 1396551ms (23 mins)

## Actual Behavior

6.5 hours and still running

## Metadata

**Typsense Version**: 0.22.0.rcs18

**OS**: running Docker on WSL on Windows 10 19043.1288
