### ISSUE TITLE
SnapshotError On Azure Kubernetes Service

### ISSUE THREAD

**Issue by Tieantono** [typesense/typesense#446]
## Description

Hi, my team are trying to use Typesense in our project to replace SQL pagination mechanisms. We are hosting the Typesense in our Azure Kubernetes Service cluster. So far is good until today, we just got an error suddenly when try to check our collections:

<details>
  <summary>Log</summary>

```
I20211129 02:02:58.219660    98 raft_server.cpp:565] Term: 2, last_index index: 4628, committed_index: 4628, known_applied_index: 4628, applying_index: 0, pending_index: 0, disk_index: 4628, pending_queue_size: 0, local_sequence: 8049
I20211129 02:02:58.219744   107 raft_server.h:58] Peer refresh succeeded!
I20211129 02:03:08.220870    98 raft_server.cpp:565] Term: 2, last_index index: 4629, committed_index: 4629, known_applied_index: 4629, applying_index: 0, pending_index: 0, disk_index: 4629, pending_queue_size: 0, local_sequence: 8049
I20211129 02:03:08.220954   107 raft_server.h:58] Peer refresh succeeded!
I20211129 02:03:10.410233   107 node.cpp:911] node default_group:10.244.1.48:8107:8108 starts to do snapshot
I20211129 02:03:10.492667   107 raft_server.cpp:468] on_snapshot_save
W20211129 02:03:11.100024   107 store.h:329] Checkpoint CreateCheckpoint failed at snapshot path: /data/state/snapshot/temp/db_snapshot, msg:IO error: while link file to /data/state/snapshot/temp/db_snapshot.tmp/000006.sst: /data/db/000006.sst: Operation not supported
E20211129 02:03:11.100109   107 raft_server.cpp:476] Failure during checkpoint creation, msg:IO error: while link file to /data/state/snapshot/temp/db_snapshot.tmp/000006.sst: /data/db/000006.sst: Operation not supported
I20211129 02:03:11.100529   107 raft_server.cpp:412] save_snapshot called
I20211129 02:03:11.109903   107 snapshot.cpp:516] Deleting /data/state/snapshot/temp
I20211129 02:03:11.124665   101 raft_server.cpp:717] Dummy write to http://10.244.1.48:8108/health, status = 200, response = {"ok":true}
I20211129 02:03:11.124922   101 raft_server.cpp:461] save_snapshot done
W20211129 02:03:11.143998   107 snapshot_executor.cpp:220] node default_group:10.244.1.48:8107:8108 fail to close writer
E20211129 02:03:11.144112   102 raft_server.h:249] Met peering error {type=SnapshotError, error_code=5, error_text=`Fail to save snapshot'}
W20211129 02:03:11.144130   102 node.cpp:1264] node default_group:10.244.1.48:8107:8108 got error={type=SnapshotError, error_code=5, error_text=`Fail to save snapshot'}
I20211129 02:03:11.144174   102 replicator.cpp:1475] Group default_group Fail to find the next candidate
I20211129 02:03:11.144209   102 raft_server.h:241] Node stepped down : Raft node(leader or candidate) is in error.
I20211129 02:03:18.236783    98 raft_server.cpp:565] Term: 2, last_index index: 4630, committed_index: 4630, known_applied_index: 4630, applying_index: 0, pending_index: 0, disk_index: 4630, pending_queue_size: 0, local_sequence: 8049
W20211129 02:03:18.236822    98 raft_server.cpp:590] Single-node with no leader. Resetting peers.
W20211129 02:03:18.236831    98 node.cpp:866] node default_group:10.244.1.48:8107:8108 is in state ERROR, can't reset_peer
``` 
</details>

Any idea what might causing this? The pod lifetime is about 10 hours. On the dev environment, we are using the `default` storage class, so far we didn't find any errors and the pod is still working for more than a week.

## Steps to reproduce

We are using these following k8s resources:
<details>
  <summary>PVC</summary>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: typesense-pvc
  namespace: staging
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile
  resources:
    requests:
      storage: 200Gi
```
</details>

<details>
  <summary>Deployment & Service</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: typesense
  namespace: staging
  labels:
    app: typesense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typesense
  template:
    metadata:
      labels:
        app: typesense
    spec:
      containers:
      - name: typesense-container
        image: typesense/typesense:0.21.0
        command: ["/opt/typesense-server", "-d", "/data", "-a", "$(ApiKey)"]
        env:
          - name: ApiKey
            valueFrom:
              secretKeyRef:
                name: typesense-secrets
                key: ApiKey
        volumeMounts:
        - mountPath: "/data"
          name: typesense-volume
      volumes:
        - name: typesense-volume
          persistentVolumeClaim:
            claimName: typesense-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: typesense-svc
  namespace: staging
spec:
  selector:
    app: typesense
  ports:
  - name: http
    port: 80
    targetPort: 8108
```
</details>

## Expected Behavior

Works without sudden error like this.

## Actual Behavior

Got error suddenly this morning about `SnapShot` error, restarting the pod temporarily fix the issue.

## Metadata

**Typsense Version**: 0.21.0

**OS**: Node image version: AKSUbuntu-1804containerd-2021.10.30, VM size: D2v3
