### ISSUE TITLE
Docker Cluster Configuration

### ISSUE THREAD

**Issue by voultest** [typesense/typesense#477]
## Description

Failed to configure docker swarm with 4 nodes: 1 manager and 3 workers.

## Steps to reproduce
We followed the steps from:
https://github.com/typesense/typesense-website/blob/2f3255286d38522fcbd668a2d97abfb710ccde60/docs-site/content/guide/high-availability.md

## Expected Behavior

We should be able to use the client libraries to do queries to typesense. It works with a single instance of docker. 

## Actual Behavior

The following errors:
```
protobuf_file.cpp:91] open file failed, path: /data/state/log/log_meta: FILE_ERROR_NOT_FOUND
log.cpp:685] /data/state/log is empty
log.cpp:1136] log save_meta /data/state/log/log_meta first_log_index: 1 time: 896
protobuf_file.cpp:91] open file failed, path: /data/state/meta/raft_meta: FILE_ERROR_NOT_FOUND
raft_meta.cpp:521] Loaded single stable meta, path /data/state/meta term 1 votedfor 0.0.0.0:0:0 time: 36
protobuf_file.cpp:91] open file failed, path: /data/state/meta/raft_meta: FILE_ERROR_NOT_FOUND
raft_meta.cpp:521] Loaded single stable meta, path /data/state/meta term 1 votedfor 0.0.0.0:0:0 time: 31
node.cpp:576] node default_group:10.0.0.16:8107:8108 init, term: 1 last_log_id: (index=0,term=0) conf: 10.0.2.2:7107:7108,10.0.2.5:9107:9108,10.0.2.8:8107:8108 old_conf: 
raft_server.cpp:127] Node last_index: 0
typesense_server_utils.cpp:260] Typesense peering service is running on 10.0.0.16:8107
typesense_server_utils.cpp:261] Snapshot interval configured as: 3600s
controller.cpp:1454] SIGINT was installed with 1
raft_server.cpp:524] Term: 1, last_index index: 0, committed_index: 0, known_applied_index: 0, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 0
raft_server.cpp:551] Multi-node with no leader: refusing to reset peers.
raft_server.cpp:524] Term: 1, last_index index: 0, committed_index: 0, known_applied_index: 0, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 0
raft_server.cpp:551] Multi-node with no leader: refusing to reset peers.
node.cpp:1484] node default_group:10.0.0.16:8107:8108 term 1 start pre_vote
node.cpp:1494] node default_group:10.0.0.16:8107:8108 can't do pre_vote as it is not in 10.0.2.2:7107:7108,10.0.2.5:9107:9108,10.0.2.8:8107:8108
node.cpp:1484] node default_group:10.0.0.16:8107:8108 term 1 start pre_vote
node.cpp:1494] node default_group:10.0.0.16:8107:8108 can't do pre_vote as it is not in 10.0.2.2:7107:7108,10.0.2.5:9107:9108,10.0.2.8:8107:8108
raft_server.cpp:524] Term: 1, last_index index: 0, committed_index: 0, known_applied_index: 0, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 0
raft_server.cpp:551] Multi-node with no leader: refusing to reset peers.
node.cpp:1484] node default_group:10.0.0.16:8107:8108 term 1 start pre_vote
node.cpp:1494] node default_group:10.0.0.16:8107:8108 can't do pre_vote as it is not in 10.0.2.2:7107:7108,10.0.2.5:9107:9108,10.0.2.8:8107:8108
node.cpp:1484] node default_group:10.0.0.16:8107:8108 term 1 start pre_vote


```## Metadata

**Typsense Version**: 0.22.1

**OS**: Debian 10

**Comment by jasonbosco** [comment]
@voultest Could you share the contents of the `nodes` files from all the nodes?

Also fyi - @ivishalgandhi is still working on tweaking those setup steps.

**Comment by voultest** [comment]
Each of the 4 nodes i.e. one manager and 3 workers has the node file containing:
typesense-1:8107:8108,typesense-2:7107:7108,typesense-3:9107:9108

Am i right in assuming that typesense-1, typesense-2, typesense-3 maps to the ip address of the manager/worker nodes in the docker container. And the reason that it works is because in the attached link I sent in the original post the service was named typesense-1, typesense-2 and typesense-3. And I assume because of that there is no need to add a host file.

**Comment by ivishalgandhi** [comment]
@voultest In Docker Swarm, during initialization additional networks are set up by docker for container and docker host communication.  Every container is assigned an IP address from the `Ingress` and `Overlay` network. During startup Typesense assigns the IP address for `peering-address` by looping all the available interfaces, this results in an IP address from the `Ingress` network assigned to `peering-address`. Resolving hostnames (Typesensenode file) uses `hostname2ip`. Due to the presence of `ingress` and `overlay` network `peering-address` and `hostname` IP address are in different `subnet`. @jasonbosco is reviewing to provide an option for `peering-subnet` so that `peering-address` and `hostname` IPs are in the same subnet to form the cluster. 

```CPP
https://github.com/typesense/typesense/blob/master/src/typesense_server_utils.cpp
const char* get_internal_ip() {
    struct ifaddrs *ifap;
    getifaddrs(&ifap);

    for(auto ifa = ifap; ifa; ifa = ifa->ifa_next) {
        if (ifa->ifa_addr && ifa->ifa_addr->sa_family==AF_INET) {
            auto sa = (struct sockaddr_in *) ifa->ifa_addr;
            if(is_private_ip(ntohl(sa->sin_addr.s_addr))) {
                char *ip = inet_ntoa(sa->sin_addr);
                freeifaddrs(ifap);
                return ip;
            }
        }
    }

    freeifaddrs(ifap);
    return "127.0.0.1";
}

https://github.com/typesense/typesense/blob/master/src/raft_server.cpp

string ReplicationState::resolve_node_hosts(const string& nodes_config) {
    std::vector<std::string> final_nodes_vec;
    std::vector<std::string> node_strings;
    StringUtils::split(nodes_config, node_strings, ",");

    for(const auto& node_str: node_strings) {
        // could be an IP or a hostname that must be resolved
        std::vector<std::string> node_parts;
        StringUtils::split(node_str, node_parts, ":");

        if(node_parts.size() != 3) {
            final_nodes_vec.push_back(node_str);
            continue;
        }

        butil::ip_t ip;
        int status = butil::hostname2ip(node_parts[0].c_str(), &ip);

        if(status == 0) {
            final_nodes_vec.push_back(
                std::string(butil::ip2str(ip).c_str()) + ":" + node_parts[1] + ":" + node_parts[2]
            );
        } else {
            LOG(ERROR) << "Unable to resolve host: " << node_parts[0];
            final_nodes_vec.push_back(node_str);
        }
    }

    std::string final_nodes_config = StringUtils::join(final_nodes_vec, ",");
    return final_nodes_config;
}
```

**Comment by ivishalgandhi** [comment]
https://github.com/typesense/typesense/issues/507

**Comment by ivishalgandhi** [comment]
@voultest  

@jasonbosco added the feature and introduced a new flag `--peering-subnet` in docker image `typesense/typesense:0.23.0.rc21`. Would you be able to re-run your tests with the below YAML, please also create a custom `overlay` network after initializing the swarm cluster. Rest all the steps are the same as documented in https://github.com/typesense/typesense-website/blob/2f3255286d38522fcbd668a2d97abfb710ccde60/docs-site/content/guide/high-availability.md#deploy-a-typesense-cluster-to-docker-swarm

``` shell 
docker network create \
  --driver overlay \
  --subnet=10.11.0.10/16 \
  --gateway=10.11.0.2 \
  --opt com.docker.network.mtu=1200 \
  ts_net
```

```yaml
version: "3.8"
services:
  typesense-1:
    image: typesense/typesense:0.23.0.rc21
    hostname: typesense-1
    volumes:
      - /tmp/typesense-data-1/:/data
      - ./nodes:/nodes
    ports:
      - 7108:7108
      - 7107:7107
    command: ["--peering-subnet","10.11.0.10/16",--data-dir", "/data","--api-key", "xyz","--nodes","/nodes","--peering-port","7107","--api-port","7108","--enable-cors"]
    deploy:
      replicas: 1
      labels:
        feature.description: “typesense-1”
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == worker]
    networks:
        - ts_net
  typesense-2:
    image: typesense/typesense:0.23.0.rc21
    hostname: typesense-2
    volumes:
      - /tmp/typesense-data-2/:/data
      - ./nodes:/nodes
    ports:
      - 8108:8108
      - 8107:8107
    command: ["--peering-subnet","10.11.0.10/16","--data-dir", "/data","--api-key", "xyz","--nodes","/nodes","--peering-port","8107","--api-port","8108","--enable-cors"]
    deploy:
      replicas: 1
      labels:
        feature.description: “typesense-2”
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == worker]
    networks:
        - ts_net
  typesense-3:
    image: typesense/typesense:0.23.0.rc21
    hostname: typesense-3
    volumes:
      - /tmp/typesense-data-3/:/data
      - ./nodes:/nodes
    ports:
      - 9108:9108
      - 9107:9107
    
    command: ["--peering-subnet","10.11.0.10/16","--data-dir", "/data","--api-key", "xyz","--nodes","/nodes","--peering-port","9107","--api-port","9108","--enable-cors"]
    deploy:
      replicas: 1
      labels:
        feature.description: “typesense-3”
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == worker]
    networks:
        - ts_net
networks:
  ts_net:
    external: true
```
