### ISSUE TITLE
How to use data from MongoDB in docker container on Typesense in the same container?

### ISSUE THREAD

**Issue by thelobao** [typesense/typesense#635]
## Description

I have a container that has a mongodb, mongo-express and typesense. I need to set that typesense use data from the mongodb inside the container. How can i do this?

I already used and configured the replica set.

## Steps to reproduce

This is my docker compose file:

```
version: "3.9"
services:
  database:
    image : 'mongo'
    container_name: 'container-name'
    environment:
      -  PUID=1000
      -  PGID=1000
    volumes:
      -  ./database:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    ports:
      -  27017:27017
    restart: unless-stopped
    
  mongo-express:
    image: mongo-express:0.54
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: database
    depends_on:
      - database

  typesense:
    image: typesense/typesense:0.21.0
    ports:
      - "8108:8108"
    environment:
      TYPESENSE_API_KEY: xyz
      TYPESENSE_DATA_DIR: /data/typesense
      TYPESENSE_ENABLE_CORS: "true"
    volumes:
      - ./typesense:/data/typesense
```

When i call the API colletions/data, i get a response and on the end i see `num_documents: 0`
