### ISSUE TITLE
Unable to run Typesense on ACI(Azure Container Instances) Segmentation fault.

### ISSUE THREAD

**Issue by niektuytel** [typesense/typesense#673]
## Description
Create a docker instance on azure with the `typesense/typesense:0.*.*` image, Terminates straight after he try to run the image in azure. 
By digging a little deeper into the container of azure we has found a `Segmentation fault` error in the `typesense/typesense:0.*.*` image.

## Steps to reproduce
- Create a local storage file inside azure, by using this [link](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files).
- The command to create a container instance into azure with the image:
```
az container create --resource-group <group-name> --name <aci-name> --image typesense/typesense:0.22.2 --ports 80 443 8108 --cpu 2 --memory 4 --restart-policy OnFailure --protocol TCP --ip-address Public -e TYPESENSE_API_KEY=mysecretapikey TYPESENSE_DATA_DIR=/data --azure-file-volume-account-name <storage-ccount> --azure-file-volume-account-key <base64-key> --azure-file-volume-share-name <storage-share-name> --azure-file-volume-mount-path /data
```  
- You can see after he start the image will terminate straight after it, to get a little output of this running process i used this command:
![image](https://user-images.githubusercontent.com/46424968/180782844-db013102-e258-4327-9ff9-fdaa2b6055ba.png)
- Than to see more inside the image, Why he is terminating? We need to use the tail function to keep the image running. [see link how we do this](https://stackoverflow.com/a/73047791/13361987)
- We connect to the image and try to run manually the typesene-server:
![image](https://user-images.githubusercontent.com/46424968/180784308-8bee551f-1828-43b3-aa19-0fb46ae74607.png)

## Expected Behavior
the expected behavior would be that is should have to work :).  
The last step for reproducing the error what gives a `Segmentation fault` should have to look like the this:(local docker typesense sample)
![image](https://user-images.githubusercontent.com/46424968/180785357-f94e9fcd-25e1-4066-b2b6-d6a5f4c49ab9.png)

What is going wrong here?

## Metadata
This is happening in ACI (Azure Container Instances) specific!  

**Typsense Version**: 0.22.2

**OS**:Linux

**Comment by kishorenc** [comment]
Without any logs, it's really difficult to understand what could be going wrong here. Isn't there no stack trace in the stdout logs?

**Comment by LucasVos** [comment]
There is literally no output, except "Segmentation fault" , as the only and immediate response.  No logs, no output. Nothing.
Is there a precompiled debug version? With symbols, etc.?

I tried `gdb typesense-server` 

```
(gdb) run
Starting program: /usr/bin/typesense-server 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff707f700 (LWP 568)]

Thread 1 "typesense-serve" received signal SIGSEGV, Segmentation fault.
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::empty (this=0x0)
    at /opt/gcc-10.1.0/build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_string.h:1002
```  

Is this something usefull?

**Comment by niektuytel** [comment]
There is no output indeed, 
Attaching local standard output and error streams by using [az container attach](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-attach) is giving the following output:  
![image](https://user-images.githubusercontent.com/46424968/181585076-57ed7e62-3646-4674-ae83-2ae9efe6ec95.png)

**Comment by jay9283743** [comment]
The reason for the segfault is that the program tries to open /proc/self/io which do not exist, so it crashes instead while trying to log the error message through glog LogMessage
The linux kernel needs TASK_IO_ACCOUNTING

**Comment by MrEcco** [comment]
Same behavior even for /bin/bash (but not for /bin/sh) in the `ubuntu:jammy` container. Just segfault and nothing else in the console :(

YAML of the ACI:
```yaml
# reference: https://learn.microsoft.com/en-us/azure/templates/microsoft.containerinstance/containergroups?pivots=deployment-language-arm-template
apiVersion: '2023-05-01'
type: Microsoft.ContainerInstance/containerGroups
name: my-test-app
location: northeurope
properties:
  osType: Linux
  sku: Confidential
  initContainers:
  - name: init
    properties:
      image: busybox:1.35.0-musl
      command:
      - /bin/sh
      - -c
      - |-
        cat <<EOF | tee /etc/docker-daemon/daemon.json
        {
            "data-root": "/var/lib/docker",
            "default-runtime": "runc",
            "default-shm-size": "64M",
            "default-address-pools": [
                {
                    "base": "172.30.0.0/15",
                    "size": 24
                }
            ],
            "hosts": [
                "unix:///var/run/docker.sock",
                "tcp://127.0.0.1:2375"
            ],
            "storage-driver": "overlay2",
            "tls": false,
            "ipv6": false
        }
        EOF
        chown root:root /etc/docker-daemon/daemon.json
        chmod 640 /etc/docker-daemon/daemon.json
      volumeMounts:
      - name: docker-config
        mountPath: /etc/docker-daemon
        readOnly: false
  containers:
  - name: main
    properties:
      image: ubuntu:jammy
      command:
      - sleep
      - "99999999"
      resources:
        requests:
          cpu: 0.5
          memoryInGb: 1
      securityContext:
        privileged: true
      volumeMounts:
      - name: build
        mountPath: /build
        readOnly: false
      - name: tmp
        mountPath: /tmp
        readOnly: false
      - name: run
        mountPath: /var/run
        readOnly: false
  - name: docker
    properties:
      image: docker:24.0.7-dind-alpine3.18
      command:
      - /usr/local/bin/dockerd
      - --config-file
      - /etc/docker-daemon/daemon.json
      resources:
        requests:
          cpu: 2
          memoryInGb: 4
      securityContext:
        privileged: true
      volumeMounts:
      - name: build
        mountPath: /build
        readOnly: false
      - name: docker-config
        mountPath: /etc/docker-daemon
        readOnly: true
      - name: docker-storage
        mountPath: /var/lib/docker
        readOnly: false
      - name: tmp
        mountPath: /tmp
        readOnly: false
      - name: run
        mountPath: /var/run
        readOnly: false
  volumes:
  - name: build
    emptyDir: {}
  - name: tmp
    emptyDir: {}
  - name: run
    emptyDir: {}
  - name: docker-config
    emptyDir: {}
  - name: docker-storage
    emptyDir: {}
  subnetIds:
    - id: /subscriptions/.../resourceGroups/.../providers/Microsoft.Network/virtualNetworks/.../subnets/...
      name: "..."
tags: {}
```

```bash
# Create
$ az container create --resource-group ... --file app.yaml
(success)

# Exec
$ az container exec --resource-group ... --name my-test-app --container-name main --exec-command /bin/bash
command terminated with non-zero exit code: error executing command [/bin/bash], exit code 139

# Exec indirect
$ az container exec --resource-group ... --name my-test-app --container-name main --exec-command /bin/sh
(passed in the container)

$ bash
Segmentation fault
$ echo $?
139
```

Please note that I granted `privileged` for both containers and cannot set capabilities manually (az cli denies it).
