### ISSUE TITLE
TYPESENSE_HEALTHY_READ_LAG didn't work

### ISSUE THREAD

**Issue by kulame** [typesense/typesense#797]
## Description

i have a typesense compose config.
```yaml
    typesense:
      image: typesense/typesense:0.23.1
      container_name: typesense
      environment:
        - TYPESENSE_API_KEY=xxxx
        - TYPESENSE_DATA_DIR=/typesense-data
        - TYPESENSE_ENABLE_CORS=true
        - TYPESENSE_HEALTHY_READ_LAG=2000000
 ```

when i reload the server and query it, it already raise error.

```bash
typesense.exceptions.ServiceUnavailable: [Errno 503] Not Ready or Lagging
```

it seems TYPESENSE_HEALTHY_READ_LAG didn't work
## Metadata

**Typesense Version**: 0.23.1

**OS**: ubuntu22.04
