### ISSUE TITLE
Kubernetes HA seems to still not work properly

### ISSUE THREAD

**Issue by abrucker235** [typesense/typesense#799]
## Description

Nodes are not able to properly join raft group.

### Configuration

```
apiVersion: v1
kind: Service
metadata:
  name: typesense
  namespace: data
spec:
  selector:
    app: typesense
  ports:
  - name: http
    port: 8108
    targetPort: 8108
---
apiVersion: v1
kind: Service
metadata:
  name: typesense-internal
  namespace: data
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: typesense
  ports:
  - name: http
    port: 8108
    targetPort: 8108
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: typesense-nodes
  namespace: data
data:
  nodes: "typesense-0.typesense-internal.data.svc.cluster.local:8107:8108,typesense-1.typesense-internal.data.svc.cluster.local:8107:8108,typesense-2.typesense-internal.data.svc.cluster.local:8107:8108"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: typesense-budget
  namespace: data
  labels:
    app: typesense
spec:
  selector:
    matchLabels:
      app: typesense
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: typesense
  namespace: data
  labels:
    app: typesense
    service: typesense
spec:
  serviceName: typesense-internal
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: typesense
  template:
    metadata:
      labels:
        app: typesense
    spec:
      serviceAccountName: typesense
      containers:
      - name: typesense
        image: typesense/typesense:0.23.1
        command:
        - "/opt/typesense-server"
        - "--data-dir"
        - "/usr/share/typesense/data"
        - "--api-port"
        - "8108"
        - "--api-address"
        - "0.0.0.0"
        - "--peering-port"
        - "8107"
        - "--nodes"
        - "/usr/share/typesense/nodes"
        - "--enable-cors"
        envFrom:
        - secretRef:
            name: typesense
        ports:
        - name: http
          containerPort: 8108
        resources:
          requests:
            cpu: "1"
            memory: 4Gi
          limits:
            cpu: "2.0"
            memory: 8Gi
        volumeMounts:
        - name: data
          mountPath: /usr/share/typesense/data
        - name: nodes
          mountPath: /usr/share/typesense
        readinessProbe:
          httpGet:
            path: "/health"
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      terminationGracePeriodSeconds: 300
      volumes:
      - name: nodes
        configMap:
          name: typesense-nodes
          items:
          - key: nodes
            path: nodes
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
```

## Steps to reproduce

```
kubectl -n data logs typesense-0
```
## Expected Behavior

Nodes should properly resolve and join each other

## Actual Behavior

```
W20221118 15:11:05.476843   326 protobuf_file.cpp:91] open file failed, path: /usr/share/typesense/data/state/log/log_meta: FILE_ERROR_NOT_FOUND
W20221118 15:11:05.476855   326 log.cpp:685] /usr/share/typesense/data/state/log is empty
I20221118 15:11:05.480769   326 log.cpp:1136] log save_meta /usr/share/typesense/data/state/log/log_meta first_log_index: 1 time: 3887
W20221118 15:11:05.480891   326 protobuf_file.cpp:91] open file failed, path: /usr/share/typesense/data/state/meta/raft_meta: FILE_ERROR_NOT_FOUND
I20221118 15:11:05.480913   326 raft_meta.cpp:521] Loaded single stable meta, path /usr/share/typesense/data/state/meta term 1 votedfor 0.0.0.0:0:0 time: 28
W20221118 15:11:05.481063   326 protobuf_file.cpp:91] open file failed, path: /usr/share/typesense/data/state/meta/raft_meta: FILE_ERROR_NOT_FOUND
I20221118 15:11:05.481078   326 raft_meta.cpp:521] Loaded single stable meta, path /usr/share/typesense/data/state/meta term 1 votedfor 0.0.0.0:0:0 time: 22
I20221118 15:11:05.481089   326 node.cpp:576] node default_group:127.0.0.1:8107:8108 init, term: 1 last_log_id: (index=0,term=0) conf: 100.64.4.64:8107:8108,100.64.4.108:8107:8108,100.64.5.169:8107:8108 old_conf: 
I20221118 15:11:05.481133   326 raft_server.cpp:129] Node last_index: 0
I20221118 15:11:05.481145   326 typesense_server_utils.cpp:301] Typesense peering service is running on 127.0.0.1:8107
I20221118 15:11:05.481153   326 typesense_server_utils.cpp:302] Snapshot interval configured as: 3600s
I20221118 15:11:05.481158   326 typesense_server_utils.cpp:303] Snapshot max byte count configured as: 4194304
W20221118 15:11:05.481176   326 controller.cpp:1454] SIGINT was installed with 1
I20221118 15:11:05.483237   326 raft_server.cpp:534] Term: 1, last_index index: 0, committed_index: 0, known_applied_index: 0, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 0
W20221118 15:11:05.483265   326 raft_server.cpp:561] Multi-node with no leader: refusing to reset peers.
I20221118 15:11:15.486498   326 raft_server.cpp:534] Term: 1, last_index index: 0, committed_index: 0, known_applied_index: 0, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 0
W20221118 15:11:15.486527   326 raft_server.cpp:561] Multi-node with no leader: refusing to reset peers.
I20221118 15:11:16.534637   346 node.cpp:1484] node default_group:127.0.0.1:8107:8108 term 1 start pre_vote
W20221118 15:11:16.534672   346 node.cpp:1494] node default_group:127.0.0.1:8107:8108 can't do pre_vote as it is not in 100.64.4.64:8107:8108,100.64.4.108:8107:8108,100.64.5.169:8107:8108
I20221118 15:11:22.314918   354 node.cpp:1484] node default_group:127.0.0.1:8107:8108 term 1 start pre_vote
W20221118 15:11:22.314952   354 node.cpp:1494] node default_group:127.0.0.1:8107:8108 can't do pre_vote as it is not in 100.64.4.64:8107:8108,100.64.4.108:8107:8108,100.64.5.169:8107:8108
I20221118 15:11:25.490043   326 raft_server.cpp:534] Term: 1, last_index index: 0, committed_index: 0, known_applied_index: 0, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 0
W20221118 15:11:25.490072   326 raft_server.cpp:561] Multi-node with no leader: refusing to reset peers.
I20221118 15:11:28.284245   346 node.cpp:1484] node default_group:127.0.0.1:8107:8108 term 1 start pre_vote
W20221118 15:11:28.284286   346 node.cpp:1494] node default_group:127.0.0.1:8107:8108 can't do pre_vote as it is not in 100.64.4.64:8107:8108,100.64.4.108:8107:8108,100.64.5.169:8107:8108
I20221118 15:11:33.573495   354 node.cpp:1484] node default_group:127.0.0.1:8107:8108 term 1 start pre_vote
W20221118 15:11:33.573531   354 node.cpp:1494] node default_group:127.0.0.1:8107:8108 can't do pre_vote as it is not in 100.64.4.64:8107:8108,100.64.4.108:8107:8108,100.64.5.169:8107:8108
I20221118 15:11:35.494029   326 raft_server.cpp:534] Term: 1, last_index index: 0, committed_index: 0, known_applied_index: 0, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 0
W20221118 15:11:35.494060   326 raft_server.cpp:561] Multi-node with no leader: refusing to reset peers.
I20221118 15:11:36.419657   327 batched_indexer.cpp:250] Running GC for aborted requests, req map size: 0
I20221118 15:11:38.748767   346 node.cpp:1484] node default_group:127.0.0.1:8107:8108 term 1 start pre_vote
W20221118 15:11:38.748805   346 node.cpp:1494] node default_group:127.0.0.1:8107:8108 can't do pre_vote as it is not in 100.64.4.64:8107:8108,100.64.4.108:8107:8108,100.64.5.169:8107:8108
I20221118 15:11:43.917032   354 node.cpp:1484] node default_group:127.0.0.1:8107:8108 term 1 start pre_vote
W20221118 15:11:43.917068   354 node.cpp:1494] node default_group:127.0.0.1:8107:8108 can't do pre_vote as it is not in 100.64.4.64:8107:8108,100.64.4.108:8107:8108,100.64.5.169:8107:8108
```

## Metadata

**Typesense Version**: 0.23.1

**OS**: kubernetes
